stages:
  - vet
  - test
  - build

lint:
  stage: vet
  image: node:8.11.4
  services:
  variables:
    NODE_ENV: development
  before_script:
    - node --version
    - npm --version
    - npm install -g eslint
  script:
    - make vet:lint
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

test-unit:
  stage: test
  image: node:8.11.4
  services:
  variables:
    NODE_ENV: test
  before_script:
    - node --version
    - npm --version
    - npm install
  script:
    - make test:unit
  cache:
    untracked: true
    paths:
      - node_modules
  except:
    - tags

test-etoe:
  stage: test
  image: node:8.11.4
  services:
  variables:
    NODE_ENV: test
    APT_CACHE_DIR: apt-cache
  before_script:
    - mkdir -pv $APT_CACHE_DIR && apt-get -qq update
    - apt-get -qq -o dir::cache::archives="$APT_CACHE_DIR" install -y
      xvfb firefox-esr
    - firefox --version
    - node --version
    - npm --version
    - npm install
    - npm run build
  script:
    - xvfb-run make test:etoe
  cache:
    untracked: true
    paths:
      - apt-cache
      - node_modules
  except:
    - tags

build:
  stage: build
  image: node:8.11.4
  services:
  variables:
    NODE_ENV: production
  before_script:
    - node --version
    - npm --version
    - npm install
  script:
    - make build
  cache:
    untracked: true
    paths:
      - node_modules
  artifacts:
    untracked: true
    paths:
      - dst
  except:
    - tags
